FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=oblivion/oblivion
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY oblivion.tar.gz /oblivion.tar.gz
RUN tar -xvf /oblivion.tar.gz

#ADD . /oblivion
RUN cd /oblivion/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /oblivion && scripts/windows-crosscompile/compile-oblivion.sh
